version: "3.9"

services:

  mlflow:
    build:
      context: ./docker/mlflow/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${MLFLOW_PORT}:5000"
    volumes:
      - ./mlruns:/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri ${MLFLOW_BACKEND_STORE}
      --default-artifact-root ${MLFLOW_ARTIFACT_ROOT}
      --host 0.0.0.0
      --port 5000

  airflow:
    build:
      context: ./docker/airflow/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
    depends_on:
      - mlflow

